-- CADASTRAR ALCUNHA PIRATA

CREATE OR REPLACE PROCEDURE CADASTRAR_ALCUNHA( CPF_PIRATA VARCHAR2, ALCUNHA VARCHAR2) IS 

BEGIN
    INSERT INTO ALCUNHA (CPF_PIRATA, ALCUNHA) VALUES (CPF_PIRATA, ALCUNHA);
    DBMS_OUTPUT.PUT_LINE ('ALCUNHA CADASTRADA COM SUCESSO!');  
END;                                                                                      