-- CADASTRAR NAVIO

CREATE OR REPLACE PROCEDURE CADASTRAR_NAVIO (CODIGO_NAVIO VARCHAR2, NOME_NAVIO VARCHAR2, MODELO VARCHAR2, CAPACIDADE NUMBER, CPF_C VARCHAR2,TIPO VARCHAR2) IS

BEGIN
    IF TIPO = 'P' THEN
        INSERT INTO NAVIO_PIRATA VALUES (CODIGO_NAVIO, NOME_NAVIO, MODELO, CAPACIDADE, CPF_C);
        DBMS_OUTPUT.PUT_LINE ('NAVIO PIRATA ' || NOME_NAVIO || ' CADASTRADO COM ÊXITO!');
    ELSIF TIPO = 'M' THEN
        INSERT INTO NAVIO_MARINHA VALUES (CODIGO_NAVIO, NOME_NAVIO, MODELO, CAPACIDADE);
        DBMS_OUTPUT.PUT_LINE ('NAVIO DA MARINHA ' || NOME_NAVIO || ' CADASTRADO COM ÊXITO!');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('TIPO DE NAVIO INVÁLIDO!');
    END IF;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O NAVIO COM CÓDIGO ' || CODIGO_NAVIO || ' JÁ ESTÁ CADASTRADO!');
END;