-- CADASTRAR_PIRATA

CREATE OR REPLACE PROCEDURE CADASTRAR_PIRATA (CPF_PIRATA VARCHAR2, NOME_PIRATA VARCHAR2, NASC_PIRATA VARCHAR2, RUM_FAV VARCHAR2, IS_CAP VARCHAR2, COD_NAVIO_P VARCHAR2) IS
    DATA_NASC DATE;
BEGIN
    DATA_NASC := TO_DATE(NASC_PIRATA, 'dd/mm/yyyy');
    IF IS_CAP = 'C' OR IS_CAP = 'T' THEN
        INSERT INTO PIRATA VALUES (CPF_PIRATA, NOME_PIRATA, DATA_NASC, NULL, RUM_FAV);
        IF IS_CAP = 'C' THEN
            INSERT INTO CAPITAO VALUES (CPF_PIRATA);
            DBMS_OUTPUT.PUT_LINE ('CAPITÃO ' || NOME_PIRATA || ' CADASTRADO COM ÊXITO!');
        ELSIF IS_CAP = 'T' THEN
            INSERT INTO TRIPULANTE VALUES (CPF_PIRATA, COD_NAVIO_P);
            DBMS_OUTPUT.PUT_LINE ('TRIPULANTE ' || NOME_PIRATA || ' CADASTRADO COM ÊXITO!');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE ('IMPOSSÍVEL CADASTRAR PIRATA!');
    END IF;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O PIRATA COM CPF ' || CPF_PIRATA || ' JÁ ESTÁ CADASTRADO!');
END;

/* :) <3 */