-- CADASTRAR BASE MILITAR

CREATE OR REPLACE PROCEDURE CADASTRAR_BASE (CODIGO_BASE VARCHAR2, NOME_BASE VARCHAR2, COORD_LONG VARCHAR2, COORD_LAT VARCHAR2) IS

BEGIN
    INSERT INTO BASE_MILITAR VALUES (CODIGO_BASE, NOME_BASE, COORD_LAT, COORD_LONG);
    DBMS_OUTPUT.PUT_LINE ('BASE MILITAR ' || NOME_BASE || ' CADASTRADA COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! A BASE MILITAR COM CÓDIGO ' || CODIGO_BASE || ' JÁ ESTÁ CADASTRADA!');
END;