-- CADASTRAR ALCUNHA PIRATA

CREATE OR REPLACE PROCEDURE CADASTRAR_ALCUNHA( CPF_PIRATA VARCHAR2, ALCUNHA VARCHAR2) IS 

BEGIN
    INSERT INTO ALCUNHA VALUES (CPF_PIRATA, ALCUNHA);
    DBMS_OUTPUT.PUT_LINE ('ALCUNHA CADASTRADA COM SUCESSO!');  
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ALCUNHA JÁ CADASTRADA PARA ESSE PIRATA!');
END;                                                                                      