-- CADASTRAR TERRITÓRIO

CREATE OR REPLACE PROCEDURE CADASTRAR_TERRITORIO (QUADRANTE VARCHAR2, NOME_TERRITORIO VARCHAR2) IS

BEGIN
    INSERT INTO TERRITORIO VALUES (QUADRANTE, NOME_TERRITORIO, NULL);
    DBMS_OUTPUT.PUT_LINE ('TERRITÓRIO ' || NOME_TERRITORIO || ' CADASTRADO COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O TERRITÓRIO NO QUADRANTE ' || QUADRANTE || ' JÁ ESTÁ CADASTRADO!');
END;