-------------------------
--------CONSULTAS--------
-------------------------

-- CONSULTA 1 (Group by/Having QTD DE PETS POR PIRATA, GROUP BY NOME, HAVING COUNT > 1):
SELECT P.NOME, COUNT(*) AS QTD_PETS
FROM PIRATA P, PET PE
WHERE P.CPF = PE.CPF_DONO
GROUP BY P.NOME
HAVING COUNT(*) > 1;


-- CONSULTA 2 (Junção interna NOME DO CAPITAO, NOME DO SEU NAVIO):
SELECT C.NOME, N.NOME
FROM CAPITAO C
INNER JOIN PIRATA P ON C.CPF = P.CPF 
INNER JOIN NAVIO_PIRATA N ON N.CPF_CAPITAO = C.CPF


-- CONSULTA 3 (Junção externa QTD DE TERRITORIOS QUE SAO PROTEGIDOS POR UMA BASE MILITAR):
SELECT B.CODIGO, COUNT(*) AS QTD_TERRITORIOS
FROM BASE_MILITAR B LEFT OUTER JOIN PROTEGE P ON B.CODIGO = P.CODIGO

-- CONSULTA 4 (Semi junção):
SELECT DISTINCT 
    *
FROM MARINHEIROS M
WHERE M.CPF IN (SELECT E.CPF EXPEDICAO E INNER JOIN NAVIO_MARINHA NM ON MN.CODIGO = E.COD_NAVIO 
                WHERE N. NOME = 'PSEUDOCONHECIDOS')


-- CONSULTA 5 (Anti-junção PIRATAS QUE NUNCA FORAM CAPTURADOS):
SELECT 
FROM PIRATA P
WHERE P.CPF NOT IN (SELECT CPF_P FROM CAPTURA C)


-- CONSULTA 6 (Subconsulta do tipo escalar QTD DE PIRATAS QUE SAO CAPITAO):
SELECT COUNT(*) FROM PIRATA P;
WHERE P.CPF IN (SELECT C.CPF FROM CAPITAO C);


-- CONSULTA 7 (Subconsulta do tipo linha CAPITAO, QTD DE PETS DELE, QTD DE TERRITORIO):
SELECT P.NOME, (SELECT COUNT(*) FROM PET
                WHERE CPF_DONO = P.CPF) AS QTD_PETS, (SELECT COUNT(*)
                                                      FROM TERRITORIO WHERE CPF_CAPITAO = P.CPF) AS QTD_TERRITORIOS
FROM PIRATA P WHERE P.CPF IN (SELECT C.CPF
                              FROM CAPITAO C
                              WHERE C.CPF = '003');

--Quantidade de expedições que o marinheiro com o maior salario participou 

select 
    COUNT(0)
from EXPEDICAO E
where E.CPF = (select
                CPF
               from (select 
                        M.CPF,
                        M.SALARIO
                     from MARINHEIRO M
                     ORDER BY SALARIO DESC)
                where rownum = 1)

-- CONSULTA 8 (Subconsulta do tipo tabela ): --TIRAR ROWNUM (ELE NÃO VIU EM SALA)



-- CONSULTA 9 (Operação de conjunto):

SELECT
    *
FROM MARINHEIRO
EXCEPT --VIU EM SALA 
SELECT 
    *
FROM MARINHEIRO M 
WHERE M.CPF NOT IN (SELECT DISTINCT CPF FROM EXPEDICAO)