-------------------------
--------CONSULTAS--------
-------------------------

-- CONSULTA 1 (GROUP BY/HAVING QTD DE PETS POR PIRATA, GROUP BY NOME, HAVING COUNT > 1):
SELECT P.NOME, COUNT(*) AS QTD_PETS
FROM PIRATA P, PET PE
WHERE P.CPF = PE.CPF_DONO
GROUP BY P.NOME
HAVING COUNT(*) > 1;

-- CONSULTA 2 (INNER JOIN NOME DO CAPITAO, NOME DO SEU NAVIO):
SELECT P.NOME AS CAPITAO, NP.NOME AS NAVIO
FROM PIRATA P INNER JOIN NAVIO_PIRATA NP ON CPF_CAPITAO = CPF
WHERE CPF IN (SELECT * FROM CAPITAO);

-- CONSULTA 3 (OUTER INNER QTD DE TERRITORIOS QUE SAO PROTEGIDOS POR UMA BASE MILITAR):
SELECT B.NOME, COUNT(*) AS QTD_TERRITORIOS_PROTEGIDOS
FROM BASE_MILITAR B LEFT OUTER JOIN PROTEGE P ON B.CODIGO = P.CODIGO
GROUP BY B.NOME;

-- CONSULTA 4 (SEMI JOIN):
SELECT DISTINCT *
FROM MARINHEIROS M
WHERE M.CPF IN (SELECT E.CPF
                FROM EXPEDICAO E INNER JOIN NAVIO_MARINHA NM ON MN.CODIGO = E.COD_NAVIO 
                WHERE NM.NOME = 'PSEUDOCONHECIDOS');

-- CONSULTA 5 (ANTI JOIN, PIRATAS QUE NUNCA FORAM CAPTURADOS):
SELECT P.NOME
FROM PIRATA P
WHERE P.CPF NOT IN (SELECT CPF_P FROM CAPTURA C)

-- CONSULTA 6 (SUBCONSULTA ESCALAR MARINHEIROS QUE POSSUEM SALARIO >= A MÉDIA SALARIAL): 
SELECT NOME
FROM MARINHEIRO M
WHERE M.SALARIO >= (SELECT AVG(M.SALARIO) FROM MARINHEIRO M);

-- CONSULTA 7 (SUBCONSULTA LINHA CAPITAO, QTD DE PETS DELE, QTD DE TERRITORIO):
SELECT P.*
FROM PIRATA P
INNER JOIN TRIPULANTE T ON T.CPF = P.CPF
WHERE (T.COD_NAVIO_P, EXTRACT(YEAR FROM TO_DATE(P.NASCIMENTO, 'dd/mm/yyyy'))) =
        (SELECT T2.COD_NAVIO_P, EXTRACT(YEAR FROM TO_DATE(P2.NASCIMENTO, 'dd/mm/yyyy'))
        FROM PIRATA P2
        INNER JOIN TRIPULANTE T2 ON T2.CPF = P2.CPF
        WHERE P2.CPF = '004');

-- CONSULTA 8 (SUBCONSULTA TABELA, NOME DOS PIRATAS QUE FORAM CAPTURADOS): 
SELECT P.NOME
FROM PIRATA P
WHERE P.CPF IN (SELECT CPF_P FROM CAPTURA);

-- CONSULTA 9 (OPERAÇÃO DE CONJUNTO, MARINHEIROS QUE NAO FORAM EM NENHUMA EXPEDICAO):
SELECT *
FROM MARINHEIRO
EXCEPT 
SELECT *
FROM MARINHEIRO M 
WHERE M.CPF NOT IN (SELECT DISTINCT CPF FROM EXPEDICAO);