-----------------------
--CRIACAO DAS TABELAS--
-----------------------

-- TABELA NAVIO_MARINHA
CREATE TABLE NAVIO_MARINHA(
    CODIGO VARCHAR2(4),
    NOME VARCHAR2(100),
    MODELO VARCHAR2(100),
    CAPACIDADE NUMBER(4),
    CONSTRAINT PK_NAVIO_MARINHA PRIMARY KEY (CODIGO)
);

-- TABELA BASE_MILITAR
CREATE TABLE BASE_MILITAR(
    CODIGO VARCHAR2(4),
    NOME VARCHAR2(100),
    COORDENADA_LATITUDE NUMBER(12),
    COORDENADA_LONGITUDE NUMBER(13),
    CONSTRAINT PK_BASE_MILITAR PRIMARY KEY (CODIGO)
);

-- TABELA MARINHEIRO
CREATE TABLE MARINHEIRO(
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    NASCIMENTO DATE,
    SALARIO NUMBER(10,2),
    CODIGO VARCHAR2(4) UNIQUE,
    CHEFE VARCHAR2(11),
    CONSTRAINT PK_MARINHEIRO PRIMARY KEY (CPF),
    CONSTRAINT FK_MARINHEIRO_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR,
    CONSTRAINT FK_MARINHEIRO_CAPITAO FOREIGN KEY (CHEFE) REFERENCES MARINHEIRO
);

-- TABELA EXPEDIÇÃO
CREATE TABLE EXPEDICAO(
    CPF VARCHAR2(11),
    QUADRANTE VARCHAR2(4),
    COD_NAVIO VARCHAR2(4),
    DATA_EXPEDICAO DATE,
    CONSTRAINT PK_EXPEDICAO PRIMARY KEY (CPF, QUADRANTE, COD_NAVIO, DATA_EXPEDICAO)
);

-- TABELA PIRATA
CREATE TABLE PIRATA(
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    NASCIMENTO DATE,
    RECOMPENSA NUMBER(10,2),
    RUM_FAVORITO VARCHAR2(100),
    CPF_MARINHEIRO VARCHAR2(11),
    QUADRANTE VARCHAR2(4),
    COD_NAVIO VARCHAR2(4),
    DATA_EXPEDICAO DATE,
    CONSTRAINT PK_PIRATA PRIMARY KEY (CPF),
    CONSTRAINT FK_PIRATA_EXPEDICAO FOREIGN KEY (QUADRANTE, CPF_MARINHEIRO, COD_NAVIO, DATA_EXPEDICAO) REFERENCES EXPEDICAO
);

-- TABELA CAPITAO
CREATE TABLE CAPITAO(
    CPF VARCHAR2(11),
    CONSTRAINT PK_CAPITAO PRIMARY KEY (CPF),
    CONSTRAINT FK_CAPITAO_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA
);

-- TABELA CHEFIA
CREATE TABLE CHEFIA(
    CPF_PIRATA VARCHAR2(11),
    CPF_CAPITAO VARCHAR2(11) NOT NULL,
    CONSTRAINT PK_CHEFIA PRIMARY KEY (CPF_PIRATA),
    CONSTRAINT FK_CHEFIA_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO,
    CONSTRAINT FK_CHEFIA_PIRATA FOREIGN KEY (CPF_PIRATA) REFERENCES PIRATA
);

-- TABELA NAVIO_PIRATA
CREATE TABLE NAVIO_PIRATA(
    CODIGO VARCHAR2(4),
    NOME VARCHAR2(100),
    MODELO VARCHAR2(100),
    CAPACIDADE NUMBER(4),
    CPF_CAPITAO VARCHAR2(11) UNIQUE NOT NULL,
    CONSTRAINT PK_NAVIO_PIRATA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_NAVIO_PIRATA_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO
);

-- TABELA ALCUNHA
CREATE TABLE ALCUNHA(
    CPF VARCHAR2(11),
    ALCUNHA VARCHAR2(100),
    CONSTRAINT PK_ALCUNHA PRIMARY KEY (CPF, ALCUNHA),
    CONSTRAINT FK_ALCUNHA_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA
);

-- TABELA TERRITORIO
CREATE TABLE TERRITORIO(
    QUADRANTE VARCHAR2(4),
    NOME VARCHAR2(100),
    CPF_CAPITAO VARCHAR2(11),
    CONSTRAINT PK_TERRITORIO PRIMARY KEY (QUADRANTE),
    CONSTRAINT FK_TERRITORIO_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO
);

-- TABELA PROTEGE
CREATE TABLE PROTEGE(
    CODIGO VARCHAR2(4),
    QUADRANTE VARCHAR2(4),
    CONSTRAINT PK_PROTEGE PRIMARY KEY (CODIGO, QUADRANTE),
    CONSTRAINT FK_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR,
    CONSTRAINT FK_TERRITORIO FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO
);

-- TABELA PET
CREATE TABLE PET(
    CODIGO VARCHAR2(4),
    CPF_DONO VARCHAR2(11),
    NOME VARCHAR2(100),
    ESPECIE VARCHAR2(100),
    CONSTRAINT PK_PET PRIMARY KEY (CPF_DONO, CODIGO),
    CONSTRAINT FK_PET FOREIGN KEY (CPF_DONO) REFERENCES PIRATA
);