-----------------------
--CRIACAO DAS TABELAS--
-----------------------

-- TABELA BASE_MILITAR
CREATE TABLE BASE_MILITAR(
    CODIGO VARCHAR2(50),
    NOME VARCHAR2(50),
    COORDENADA_LATITUDE NUMBER(12),
    COORDENADA_LONGITUDE NUMBER(13),
    CONSTRAINT PK_BASE_MILITAR PRIMARY KEY (CODIGO)
);

-- TABELA MARINHEIRO
CREATE TABLE MARINHEIRO(
    CPF VARCHAR2(11),
    NOME VARCHAR2(50),
    NASCIMENTO DATE,
    SALARIO NUMBER(10,2),
    CODIGO VARCHAR2(50) UNIQUE,
    CHEFE VARCHAR2(11),
    CONSTRAINT PK_MARINHEIRO PRIMARY KEY (CPF),
    CONSTRAINT FK_MARINHEIRO_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR,
    CONSTRAINT FK_MARINHEIRO_CAPITAO FOREIGN KEY (CHEFE) REFERENCES MARINHEIRO
);

-- TABELA NAVIO_MARINHA
CREATE TABLE NAVIO_MARINHA(
    CODIGO VARCHAR2(50),
    NOME VARCHAR2(50),
    MODELO VARCHAR2(50),
    CAPACIDADE NUMBER(4),
    CONSTRAINT PK_NAVIO_MARINHA PRIMARY KEY (CODIGO)
);

-- TABELA EXPEDIÇÃO
CREATE TABLE EXPEDICAO(
    CPF VARCHAR2(11),
    QUADRANTE VARCHAR2(50),
    COD_NAVIO VARCHAR2(50),
    DATA_EXPEDICAO DATE,
    CONSTRAINT PK_EXPEDICAO PRIMARY KEY (CPF, QUADRANTE, COD_NAVIO, DATA_EXPEDICAO)
);

CREATE TABLE PIRATA( 
    CPF VARCHAR2(11), 
    NOME VARCHAR2(50), 
    NASCIMENTO DATE, 
    RECOMPENSA NUMBER(10,2), 
    RUM_FAVORITO VARCHAR2(50), 
    CPF_MARINHEIRO VARCHAR2(11), 
    QUADRANTE VARCHAR2(50), 
    COD_NAVIO_M VARCHAR2(50), 
    DATA_EXPEDICAO DATE, 
    CONSTRAINT PK_PIRATA PRIMARY KEY (CPF), 
    CONSTRAINT FK_PIRATA_EXPEDICAO FOREIGN KEY (CPF_MARINHEIRO, QUADRANTE, COD_NAVIO_M, DATA_EXPEDICAO) REFERENCES EXPEDICAO 
);

-- TABELA CAPITAO
CREATE TABLE CAPITAO(
    CPF VARCHAR2(11),
    CONSTRAINT PK_CAPITAO_PIRATA PRIMARY KEY (CPF),
    CONSTRAINT FK_CAPITAO FOREIGN KEY (CPF) REFERENCES PIRATA
);

-- TABELA NAVIO_PIRATA
CREATE TABLE NAVIO_PIRATA(
    CODIGO VARCHAR2(50),
    NOME VARCHAR2(50),
    MODELO VARCHAR2(50),
    CAPACIDADE NUMBER(4),
    CPF_CAPITAO VARCHAR2(11) UNIQUE NOT NULL,
    CONSTRAINT PK_NAVIO_PIRATA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_NAVIO_PIRATA_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO
);

-- TABELA CAPITAO
CREATE TABLE TRIPULACAO(
    CPF VARCHAR2(11),
    COD_NAVIO_P VARCHAR2(50),
    CONSTRAINT PK_TRIPULACAO PRIMARY KEY (CPF),
    CONSTRAINT FK_TRIPULACAO_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA,
    CONSTRAINT FK_TRIPULACAO_NAVIO FOREIGN KEY (COD_NAVIO_P) REFERENCES NAVIO_PIRATA
);

-- TABELA ALCUNHA
CREATE TABLE ALCUNHA(
    CPF VARCHAR2(11),
    ALCUNHA VARCHAR2(50),
    CONSTRAINT PK_ALCUNHA PRIMARY KEY (CPF, ALCUNHA),
    CONSTRAINT FK_ALCUNHA_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA
);

-- TABELA TERRITORIO
CREATE TABLE TERRITORIO(
    QUADRANTE VARCHAR2(50),
    NOME VARCHAR2(50),
    CPF_CAPITAO VARCHAR2(11),
    CONSTRAINT PK_TERRITORIO PRIMARY KEY (QUADRANTE),
    CONSTRAINT FK_TERRITORIO_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO
);

-- TABELA PROTEGE
CREATE TABLE PROTEGE(
    CODIGO VARCHAR2(50),
    QUADRANTE VARCHAR2(50),
    CONSTRAINT PK_PROTEGE PRIMARY KEY (CODIGO, QUADRANTE),
    CONSTRAINT FK_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR,
    CONSTRAINT FK_TERRITORIO FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO
);

-- TABELA PET
CREATE TABLE PET(
    CODIGO VARCHAR2(50),
    CPF_DONO VARCHAR2(11),
    NOME VARCHAR2(50),
    ESPECIE VARCHAR2(50),
    CONSTRAINT PK_PET PRIMARY KEY (CPF_DONO, CODIGO),
    CONSTRAINT FK_PET FOREIGN KEY (CPF_DONO) REFERENCES PIRATA
);