-------------------------
-------PROGRAMAÇÃO-------
-------------------------

-- CADASTRAR BASE MILITAR (PROCEDURE)
CREATE OR REPLACE PROCEDURE CADASTRAR_BASE (CODIGO_BASE VARCHAR2, NOME_BASE VARCHAR2, COORD_LONG VARCHAR2, COORD_LAT VARCHAR2) IS

BEGIN
    INSERT INTO BASE_MILITAR VALUES (CODIGO_BASE, NOME_BASE, COORD_LAT, COORD_LONG);
    DBMS_OUTPUT.PUT_LINE ('BASE MILITAR ' || NOME_BASE || ' CADASTRADA COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! A BASE MILITAR COM CÓDIGO ' || CODIGO_BASE || ' JÁ ESTÁ CADASTRADA!');
END;

-- CADASTRAR MARINHEIRO (PROCEDURE)
CREATE OR REPLACE PROCEDURE CADASTRAR_MARINHEIRO (CPF_MARINHEIRO VARCHAR2, NOME_MARINHEIRO VARCHAR2, NASC_MARINHEIRO VARCHAR2, SALARIO NUMBER, COD_BASE VARCHAR2, CPF_CHEFE VARCHAR2) IS
    DATA_NASC DATE;
BEGIN
    DATA_NASC := TO_DATE(NASC_MARINHEIRO, 'dd/mm/yyyy');
    INSERT INTO MARINHEIRO VALUES (CPF_MARINHEIRO, NOME_MARINHEIRO, DATA_NASC, SALARIO, COD_BASE, CPF_CHEFE);
    DBMS_OUTPUT.PUT_LINE ('MARINHEIRO ' || NOME_MARINHEIRO || ' CADASTRADO COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O MARINHEIRO COM CPF ' || CPF_MARINHEIRO || ' JÁ ESTÁ CADASTRADO!');
END;

-- CADASTRAR_PIRATA (PROCEDURE)
CREATE OR REPLACE PROCEDURE CADASTRAR_PIRATA (CPF_PIRATA VARCHAR2, NOME_PIRATA VARCHAR2, NASC_PIRATA VARCHAR2, RUM_FAV VARCHAR2, IS_CAP VARCHAR2, COD_NAVIO_P VARCHAR2) IS
    DATA_NASC DATE;
BEGIN
    DATA_NASC := TO_DATE(NASC_PIRATA, 'dd/mm/yyyy');
    IF IS_CAP = 'C' OR IS_CAP = 'T' THEN
        INSERT INTO PIRATA VALUES (CPF_PIRATA, NOME_PIRATA, DATA_NASC, NULL, RUM_FAV);
        IF IS_CAP = 'C' THEN
            INSERT INTO CAPITAO VALUES (CPF_PIRATA);
            DBMS_OUTPUT.PUT_LINE ('CAPITÃO ' || NOME_PIRATA || ' CADASTRADO COM ÊXITO!');
        ELSIF IS_CAP = 'T' THEN
            INSERT INTO TRIPULANTE VALUES (CPF_PIRATA, COD_NAVIO_P);
            DBMS_OUTPUT.PUT_LINE ('TRIPULANTE ' || NOME_PIRATA || ' CADASTRADO COM ÊXITO!');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE ('IMPOSSÍVEL CADASTRAR PIRATA!');
    END IF;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O PIRATA COM CPF ' || CPF_PIRATA || ' JÁ ESTÁ CADASTRADO!');
END;

-- CADASTRAR NAVIO (PROCEDURE)
CREATE OR REPLACE PROCEDURE CADASTRAR_NAVIO (CODIGO_NAVIO VARCHAR2, NOME_NAVIO VARCHAR2, MODELO VARCHAR2, CAPACIDADE NUMBER, CPF_C VARCHAR2,TIPO VARCHAR2) IS

BEGIN
    IF TIPO = 'P' THEN
        INSERT INTO NAVIO_PIRATA VALUES (CODIGO_NAVIO, NOME_NAVIO, MODELO, CAPACIDADE, CPF_C);
        DBMS_OUTPUT.PUT_LINE ('NAVIO PIRATA ' || NOME_NAVIO || ' CADASTRADO COM ÊXITO!');
    ELSIF TIPO = 'M' THEN
        INSERT INTO NAVIO_MARINHA VALUES (CODIGO_NAVIO, NOME_NAVIO, MODELO, CAPACIDADE);
        DBMS_OUTPUT.PUT_LINE ('NAVIO DA MARINHA ' || NOME_NAVIO || ' CADASTRADO COM ÊXITO!');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('TIPO DE NAVIO INVÁLIDO!');
    END IF;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O NAVIO COM CÓDIGO ' || CODIGO_NAVIO || ' JÁ ESTÁ CADASTRADO!');
END;

-- CADASTRAR TERRITÓRIO (PROCEDURE)
CREATE OR REPLACE PROCEDURE CADASTRAR_TERRITORIO (QUADRANTE VARCHAR2, NOME_TERRITORIO VARCHAR2) IS

BEGIN
    INSERT INTO TERRITORIO VALUES (QUADRANTE, NOME_TERRITORIO, NULL);
    DBMS_OUTPUT.PUT_LINE ('TERRITÓRIO ' || NOME_TERRITORIO || ' CADASTRADO COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O TERRITÓRIO NO QUADRANTE ' || QUADRANTE || ' JÁ ESTÁ CADASTRADO!');
END;

-- ADOTAR UM PET (PROCEDURE)
CREATE OR REPLACE PROCEDURE ADOTAR_PET (CODIGO_PET VARCHAR2, CPF_DONO VARCHAR2, NOME_PET VARCHAR2, ESPECIE VARCHAR2) IS

BEGIN 
    INSERT INTO PET VALUES (CODIGO_PET, CPF_DONO, NOME_PET, ESPECIE);
    DBMS_OUTPUT.PUT_LINE ('PARABÉNS, ' || NOME_PET || ' FOI ADOTADO COM ÊXITO!');
END;

-- VERIFICAR O CAPITÃO PIRATA (FUNCTION)


-- DESIGNAR RECOMPENSA PELO PIRATA (PROCEDURE)
CREATE OR REPLACE PROCEDURE DESIGNAR_RECOMPENSA (CPF_PIRATA VARCHAR2, VALOR NUMBER) IS

BEGIN
    UPDATE PIRATA SET RECOMPENSA = VALOR;
    DBMS_OUTPUT.PUT_LINE ('RECOMPENSA DESIGNADA COM ÊXITO!');
END;

-- VERIFICAR RECOMPENSA PELO PIRATA (FUNCTION)


-- PROTEGER TERRITÓRIO (PROCEDURE)


-- DOMINAR TERRITÓRIO (PROCEDURE)
CREATE OR REPLACE PROCEDURE DOMINAR_TERRITORIO (QUADRANTE VARCHAR2, CPF_PIRATA VARCHAR2) IS

BEGIN
    UPDATE TERRITORIO SET CPF_PIRATA = CPF_PIRATA WHERE (SELECT IS_CAP FROM );
    DBMS_OUTPUT.PUT_LINE ('TERRITÓRIO DOMINADO COM ÊXITO!');
END;

-- REALIZAR EXPEDIÇÃO (PROCEDURE)


-- CAPTURAR PIRATA (PROCEDURE)


-- VERIFICAR DATA DA EXPEDIÇÃO (FUNCTION)


-- VERIFICAR IDADE DAS PESSOAS (FUNCTION)