-------------------------
-------PROGRAMAÇÃO-------
-------------------------

-- CADASTRAR BASE MILITAR (PROCEDURE)
CREATE OR REPLACE PROCEDURE CADASTRAR_BASE (CODIGO_BASE VARCHAR2, NOME_BASE VARCHAR2, COORD_LONG VARCHAR2, COORD_LAT VARCHAR2) IS

BEGIN
    INSERT INTO BASE_MILITAR VALUES (CODIGO_BASE, NOME_BASE, COORD_LAT, COORD_LONG);
END

-- INGRESSAR NA TRIPULAÇÃO DA MARINHA (PROCEDURE)
CREATE OR REPLACE PROCEDURE INGRESSAR_MARINHA (CPF VARCHAR2, NOME_MARINHA VARCHAR2, DT_NASC DATE, SALARIO NUMBER, CHEFIA NUMBER, COD_BASE VARCHAR2) IS

BEGIN

END

-- INGRESSAR NA TRIPULAÇÃO DE PIRATAS (PROCEDURE)


-- VERIFICAR CAPITÃO PIRATA (FUNCTION)


-- DESIGNAR RECOMPENSA PELO PIRATA (PROCEDURE)


-- VERIFICAR RECOMPENSA PELO PIRATA (FUNCTION)


-- CADASTRAR TERRITÓRIO (PROCEDURE)


-- PROTEGER TERRITÓRIO (PROCEDURE)


-- DOMINAR TERRITÓRIO (PROCEDURE)


-- CADASTRAR NAVIO (PROCEDURE)


-- ADOTAR UM PET (PROCEDURE)


-- REALIZAR EXPEDIÇÃO (PROCEDURE)


-- CAPTURAR PIRATA (PROCEDURE)


-- VERIFICAR DATA DA EXPEDIÇÃO (FUNCTION)


-- VERIFICAR IDADE DAS PESSOAS (FUNCTION)