-- TABELA ALCUNHA
CREATE TABLE ALCUNHA(
    CPF VARCHAR2(11),
    ALCUNHA VARCHAR2(100),
    CONSTRAINT PK_ALCUNHA PRIMARY KEY (CPF, ALCUNHA),
    CONSTRAINT FK_ALCUNHA_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA
);
