-- TABELA BASE_MILITAR
CREATE TABLE BASE_MILITAR(
    CODIGO VARCHAR2(4),
    NOME VARCHAR2(100),
    COORDENADA_LATITUDE VARCHAR2(12),
    COORDENADA_LONGITUDE VARCHAR2(13),
    CONSTRAINT PK_BASE_MILITAR PRIMARY KEY (CODIGO)
);