-- TABELA CAPTURA
CREATE TABLE CAPTURA(
    CPF_P VARCHAR2(11),
    CPF_M VARCHAR2(11),
    QUADRANTE VARCHAR2(4),
    COD_NAVIO VARCHAR2(4),
    DATA_CAPTURA VARCHAR2(50),
    CONSTRAINT PK_CAPTURA PRIMARY KEY (CPF_P, CPF_M, QUADRANTE, COD_NAVIO, DATA_CAPTURA),
    CONSTRAINT FK_CAPTURA_PIRATA FOREIGN KEY (CPF_P) REFERENCES PIRATA,
    CONSTRAINT FK_CAPTURA_MARINHEIRO FOREIGN KEY (CPF_M) REFERENCES MARINHEIRO,
    CONSTRAINT FK_CAPTURA_QUADRANTE FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO,
    CONSTRAINT FK_CAPTURA_NAVIO FOREIGN KEY (COD_NAVIO) REFERENCES NAVIO_MARINHA
);
