-- TABELA EXPEDIÇÃO
CREATE TABLE EXPEDICAO(
    CPF VARCHAR2(11),
    QUADRANTE VARCHAR2(4),
    COD_NAVIO VARCHAR2(4),
    DATA_EXPEDICAO VARCHAR2(50),
    CONSTRAINT PK_EXPEDICAO PRIMARY KEY (CPF, QUADRANTE, COD_NAVIO, DATA_EXPEDICAO),
    CONSTRAINT FK_EXPEDICAO_CPF FOREIGN KEY (CPF) REFERENCES MARINHEIRO,
    CONSTRAINT FK_EXPEDICAO_QUADRANTE FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO,
    CONSTRAINT FK_EXPEDICAO_NAVIO FOREIGN KEY (COD_NAVIO) REFERENCES NAVIO_MARINHA
);