-- TABELA NAVIO_PIRATA
CREATE TABLE NAVIO_PIRATA(
    CODIGO VARCHAR2(4),
    NOME VARCHAR2(100),
    MODELO VARCHAR2(100),
    CAPACIDADE NUMBER(4),
    CPF_CAPITAO VARCHAR2(11) UNIQUE NOT NULL,
    CONSTRAINT PK_NAVIO_PIRATA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_NAVIO_PIRATA_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO
);