-- TABELA NAVIO_MARINHA
CREATE TABLE NAVIO_MARINHA(
    CODIGO VARCHAR2(4),
    NOME VARCHAR2(100),
    MODELO VARCHAR2(100),
    CAPACIDADE NUMBER(4),
    CONSTRAINT PK_NAVIO_MARINHA PRIMARY KEY (CODIGO)
);