-- TABELA PET
CREATE TABLE PET(
    CODIGO VARCHAR2(4),
    CPF_DONO VARCHAR2(11),
    NOME VARCHAR2(100),
    ESPECIE VARCHAR2(100),
    CONSTRAINT PK_PET PRIMARY KEY (CPF_DONO, CODIGO),
    CONSTRAINT FK_PET FOREIGN KEY (CPF_DONO) REFERENCES PIRATA
);