CREATE TABLE PIRATA( 
    CPF VARCHAR2(11), 
    NOME VARCHAR2(100), 
    NASCIMENTO VARCHAR2(50), 
    RECOMPENSA NUMBER(10,2), 
    RUM_FAVORITO VARCHAR2(100),
    CONSTRAINT PK_PIRATA PRIMARY KEY (CPF)
);
