-- TABELA PROTEGE
CREATE TABLE PROTEGE(
    CODIGO VARCHAR2(4),
    QUADRANTE VARCHAR2(4),
    CONSTRAINT PK_PROTEGE PRIMARY KEY (CODIGO, QUADRANTE),
    CONSTRAINT FK_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR,
    CONSTRAINT FK_TERRITORIO FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO
);