-- TABELA TRIPULANTE
--TODO CPF TEM QUE SER UNIQUE
CREATE TABLE TRIPULANTE(
    CPF VARCHAR2(11),
    COD_NAVIO_P VARCHAR2(4),
    CONSTRAINT PK_TRIPULANTE PRIMARY KEY (CPF),
    CONSTRAINT FK_TRIPULANTE_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA,
    CONSTRAINT FK_TRIPULANTE_NAVIO FOREIGN KEY (COD_NAVIO_P) REFERENCES NAVIO_PIRATA
);