-- ADOTAR UM PET

CREATE OR REPLACE PROCEDURE ADOTAR_PET (CODIGO_PET VARCHAR2, CPF_DONO VARCHAR2, NOME_PET VARCHAR2, ESPECIE VARCHAR2) IS

BEGIN 
    INSERT INTO PET VALUES (CODIGO_PET, CPF_DONO, NOME_PET, ESPECIE);
    DBMS_OUTPUT.PUT_LINE ('PARABÉNS, ' || NOME_PET || ' FOI ADOTADO COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O PET COM CÓDIGO ' || CODIGO_PET || ' JÁ ESTÁ CADASTRADO!');
END;