-- DESIGNAR RECOMPENSA PELO PIRATA
-- CONSERTAR IF/ELSE

CREATE OR REPLACE PROCEDURE DESIGNAR_RECOMPENSA (CPF_PIRATA VARCHAR2, VALOR NUMBER) IS 
	CPF_PI VARCHAR(11);
BEGIN 
    SELECT CPF INTO CPF_PI
    FROM PIRATA
    WHERE CPF = CPF_PIRATA;

    IF CPF_PI IS NOT NULL THEN
        UPDATE PIRATA SET RECOMPENSA = VALOR;
        WHERE CPF = CPF_PI;
        DBMS_OUTPUT.PUT_LINE ('RECOMPENSA DE R$' || VALOR || ' DESIGNADA COM ÊXITO!'); 
    ELSE 
        DBMS_OUTPUT.PUT_LINE ('CPF NÃO EXISTE, IMPOSSÍVEL DESIGNAR RECOMPENSA!'); 
    END IF;
END;