-- DOMINAR TERRITÓRIO

CREATE OR REPLACE PROCEDURE DOMINAR_TERRITORIO (QUADRANTE_TER VARCHAR2, CPF_CAP VARCHAR2) IS
    CAP_TER VARCHAR2(11);
    NOME_CAP VARCHAR2(100);
    NOME_TER VARCHAR2(100);
    PROTEGE_TER VARCHAR2(4);
BEGIN
    SELECT 
        P.NOME INTO NOME_CAP 
    FROM CAPITAO C, PIRATA P 
    WHERE P.CPF = C.CPF AND P.CPF = CPF_CAP;

    SELECT 
        NOME INTO NOME_TER 
    FROM TERRITORIO 
    WHERE QUADRANTE = QUADRANTE_TER;

    SELECT
        QUADRANTE INTO PROTEGE_TER
    FROM PROTEGE 
    WHERE QUADRANTE = QUADRANTE_TER;
    
    IF PROTEGE_TER IS NULL THEN

        SELECT 
            CPF_CAPITAO INTO CAP_TER
        FROM TERRITORIO
        WHERE QUADRANTE = QUADRANTE_TER;

        IF CAP_TER IS NULL THEN 
            UPDATE TERRITORIO 
                SET CPF_CAPITAO = CPF_CAP 
            WHERE CPF_CAP IN (SELECT CPF FROM CAPITAO)
            AND QUADRANTE = QUADRANTE_TER;
            DBMS_OUTPUT.PUT_LINE ('O TERRITÓRIO ' || NOME_TER ||' FOI DOMINADO POR '|| NOME_CAP ||'!');
        ELSE 
            DBMS_OUTPUT.PUT_LINE ('ERRO! O TERRITÓRIO ' || QUADRANTE_TER || ' JÁ FOI DOMINADO!');
        END IF;
    
    ELSE
        DBMS_OUTPUT.PUT_LINE ('ERRO! O TERRITÓRIO ' || NOME_TER || ' ESTÁ SENDO PROTEGIDO POR UMA BASE MARINHA!');
    END IF;
    
END;

