-- FUGIR DA PRISÃO
-- CONSERTAR IF/ELSE

CREATE OR REPLACE PROCEDURE FUGIR_PRISAO (CPF_PIRATA VARCHAR2) IS
    CPF_PI VARCHAR(11);
BEGIN
    CPF_PI := NULL; 
    SELECT CPF_P INTO CPF_PI FROM CAPTURA WHERE CPF_P = CPF_PIRATA;
    IF CPF_PI = CPF_PIRATA THEN
        DELETE FROM CAPTURA WHERE CPF_P = CPF_PIRATA;
        DBMS_OUTPUT.PUT_LINE ('O PIRATA DE CPF ' || CPF_PIRATA || ' FUGIU DA PRISÃO!'); 
    ELSE
        DBMS_OUTPUT.PUT_LINE ('CPF NÃO CADASTRADO NA PRISÃO, IMPOSSÍVEL FUGIR!'); 
    END IF;
END;