-- PROTEGER TERRITÓRIO

CREATE OR REPLACE PROCEDURE PROTEGER_TERRITORIO (COD_BASE VARCHAR2, QUADRANTE_TER VARCHAR2) IS
    CPF_CAP VARCHAR2(11);
BEGIN
    SELECT CPF_CAPITAO INTO CPF_CAP
    FROM TERRITORIO
    WHERE QUADRANTE = QUADRANTE_TER;

    IF CPF_CAP IS NULL THEN
        INSERT INTO PROTEGE VALUES (COD_BASE, QUADRANTE_TER);
        DBMS_OUTPUT.PUT_LINE ('TERRITÓRIO ' || QUADRANTE_TER || ' PROTEGIDO COM ÊXITO!');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('ERRO! O TERRITÓRIO ' || QUADRANTE_TER || ' É DOMINADO POR PIRATAS! :O');
    END IF;
END;