-- PROTEGER TERRITÓRIO

CREATE OR REPLACE PROCEDURE PROTEGER_TERRITORIO (COD_BASE VARCHAR2, QUADRANTE_TER VARCHAR2) IS

BEGIN
    INSERT INTO PROTEGE VALUES (COD_BASE, QUADRANTE_TER);
    DBMS_OUTPUT.PUT_LINE ('TERRITÓRIO ' || QUADRANTE_TER || ' PROTEGIDO COM ÊXITO!');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE ('ERRO! O TERRITÓRIO NO QUADRANTE ' || QUADRANTE_TER || ' JÁ ESTÁ PROTEGIDO!');
END;