-- VERIFICAR A SOMA DA RECOMPENSA DE TODOS OS TRIPULANTES DO NAVIO

CREATE OR REPLACE FUNCTION RECOMPENSA_POR_NAVIO (COD_NAVIO_P VARCHAR2) RETURN NUMBER IS
    RECOMPENSA_1 NUMBER(10,2);
    RECOMPENSA_2 NUMBER(10,2);
    RECOMPENSA_TOTAL NUMBER(10,2);
BEGIN

    SELECT SUM(P.RECOMPENSA) INTO RECOMPENSA_1
    FROM TRIPULANTE T, PIRATA P, CAPITAO C
    WHERE (T.CPF = P.CPF AND T.COD_NAVIO_P = COD_NAVIO_P)
    AND P.RECOMPENSA IS NOT NULL;

    SELECT SUM(P.RECOMPENSA) INTO RECOMPENSA_2
    FROM PIRATA P, NAVIO_PIRATA N, CAPITAO C
    WHERE (C.CPF = P.CPF
    AND N.CPF_CAPITAO = C.CPF
    AND N.CODIGO = COD_NAVIO_P
    AND P.RECOMPENSA IS NOT NULL);

    SELECT RECOMPENSA_1 + RECOMPENSA_2 INTO RECOMPENSA_TOTAL
    FROM DUAL;

    RETURN RECOMPENSA_TOTAL;
END;