-- VERIFICAR IDADE DAS PESSOAS

CREATE OR REPLACE FUNCTION VERIFICAR_IDADE_FIM_DO_ANO (CPF_P VARCHAR2) RETURN NUMBER IS
    IDADE NUMBER(3);
BEGIN
    SELECT
        EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DATA_NASCIMENTO) INTO IDADE
    FROM PIRATA
    WHERE CPF = CPF_P;

    RETURN IDADE;
END;