--TODO : FASZER FUNCIONAR 
CREATE OR REPLACE FUNCTION VERIFICAR_IDADE_FIM_DO_ANO (CPF_P VARCHAR2) RETURN INT IS
    IDADE INT;
    DATA_NASCIMENTO DATE;
BEGIN
    SELECT TO_DATE(NASCIMENTO, 'dd/mm/yyyy') INTO DATA_NASCIMENTO
    FROM PIRATA
    WHERE CPF = CPF_P;
	
    -- Calcula a idade com base na diferença em meses entre a data de nascimento e a data atual
    IDADE := TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_NASCIMENTO) / 12);

    RETURN IDADE;
END;