create or replace procedure pr_init_all_constraint is
begin
-- ADICIONA AS CONSTRAINTS 

    -- Adicionar a chave primária para a tabela BASE_MILITAR
    EXECUTE IMMEDIATE 'ALTER TABLE BASE_MILITAR ADD CONSTRAINT PK_BASE_MILITAR PRIMARY KEY (CODIGO)';
    
    -- Adicionar as constraints de chave estrangeira para a tabela MARINHEIRO
    EXECUTE IMMEDIATE 'ALTER TABLE MARINHEIRO 
        ADD CONSTRAINT FK_MARINHEIRO_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR';
    EXECUTE IMMEDIATE 'ALTER TABLE MARINHEIRO 
        ADD CONSTRAINT FK_MARINHEIRO_CAPITAO FOREIGN KEY (CHEFE) REFERENCES MARINHEIRO';
    
    -- Adicionar a constraint de chave estrangeira para a tabela CAPITAO
    EXECUTE IMMEDIATE 'ALTER TABLE CAPITAO ADD CONSTRAINT FK_CAPITAO FOREIGN KEY (CPF) REFERENCES PIRATA';
    
    -- Adicionar a constraint de chave estrangeira para a tabela NAVIO_PIRATA
    EXECUTE IMMEDIATE 'ALTER TABLE NAVIO_PIRATA
        ADD CONSTRAINT FK_NAVIO_PIRATA_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO';
    
    -- Adicionar as constraints de chave estrangeira para a tabela TRIPULANTE
    EXECUTE IMMEDIATE 'ALTER TABLE TRIPULANTE 
        ADD CONSTRAINT FK_TRIPULANTE_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA';
    EXECUTE IMMEDIATE 'ALTER TABLE TRIPULANTE 
        ADD CONSTRAINT FK_TRIPULANTE_NAVIO FOREIGN KEY (COD_NAVIO_P) REFERENCES NAVIO_PIRATA';
    
    -- Adicionar a constraint de chave estrangeira para a tabela ALCUNHA
    EXECUTE IMMEDIATE 'ALTER TABLE ALCUNHA 
        ADD CONSTRAINT FK_ALCUNHA_PIRATA FOREIGN KEY (CPF) REFERENCES PIRATA';
    
    -- Adicionar a constraint de chave estrangeira para a tabela PET
    EXECUTE IMMEDIATE 'ALTER TABLE PET 
        ADD CONSTRAINT FK_PET FOREIGN KEY (CPF_DONO) REFERENCES PIRATA';
    
    -- Adicionar a constraint de chave estrangeira para a tabela TERRITORIO
    EXECUTE IMMEDIATE 'ALTER TABLE TERRITORIO 
        ADD CONSTRAINT FK_TERRITORIO_CAPITAO FOREIGN KEY (CPF_CAPITAO) REFERENCES CAPITAO';
    
    -- Adicionar as constraints de chave estrangeira para a tabela EXPEDICAO
    EXECUTE IMMEDIATE 'ALTER TABLE EXPEDICAO 
        ADD CONSTRAINT FK_EXPEDICAO_CPF FOREIGN KEY (CPF) REFERENCES MARINHEIRO';
    EXECUTE IMMEDIATE 'ALTER TABLE EXPEDICAO 
        ADD CONSTRAINT FK_EXPEDICAO_QUADRANTE FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO';
    EXECUTE IMMEDIATE 'ALTER TABLE EXPEDICAO 
        ADD CONSTRAINT FK_EXPEDICAO_NAVIO FOREIGN KEY (COD_NAVIO) REFERENCES NAVIO_MARINHA';
    
    -- Adicionar as constraints de chave estrangeira para a tabela CAPTURA
    EXECUTE IMMEDIATE 'ALTER TABLE CAPTURA 
        ADD CONSTRAINT FK_CAPTURA_PIRATA FOREIGN KEY (CPF_P) REFERENCES PIRATA';
    EXECUTE IMMEDIATE 'ALTER TABLE CAPTURA 
        ADD CONSTRAINT FK_CAPTURA_MARINHEIRO FOREIGN KEY (CPF_M) REFERENCES MARINHEIRO';
    EXECUTE IMMEDIATE 'ALTER TABLE CAPTURA 
        ADD CONSTRAINT FK_CAPTURA_QUADRANTE FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO';
    EXECUTE IMMEDIATE 'ALTER TABLE CAPTURA 
        ADD CONSTRAINT FK_CAPTURA_NAVIO FOREIGN KEY (COD_NAVIO) REFERENCES NAVIO_MARINHA';
    
    -- Adicionar as constraints de chave estrangeira para a tabela PROTEGE 
    EXECUTE IMMEDIATE 'ALTER TABLE PROTEGE 
        ADD CONSTRAINT FK_BASE FOREIGN KEY (CODIGO) REFERENCES BASE_MILITAR';
    EXECUTE IMMEDIATE 'ALTER TABLE PROTEGE 
        ADD CONSTRAINT FK_TERRITORIO FOREIGN KEY (QUADRANTE) REFERENCES TERRITORIO';
end;