CREATE OR REPLACE PROCEDURE pr_init_all_tables IS
    table_exists BOOLEAN;
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE BASE_MILITAR(
        CODIGO VARCHAR2(4),
        NOME VARCHAR2(100),
        COORDENADA_LATITUDE VARCHAR2(12),
        COORDENADA_LONGITUDE VARCHAR2(13),
        CONSTRAINT PK_BASE_MILITAR PRIMARY KEY (CODIGO)
    )';
    
    -- TABELA MARINHEIRO
    EXECUTE IMMEDIATE 'CREATE TABLE MARINHEIRO(
        CPF VARCHAR2(11),
        NOME VARCHAR2(100),
        NASCIMENTO VARCHAR2(50),
        SALARIO NUMBER(10,2),
        CODIGO VARCHAR2(4) NOT NULL,
        CHEFE VARCHAR2(11),
        CONSTRAINT PK_MARINHEIRO PRIMARY KEY (CPF)
    )';
    
    -- TABELA NAVIO_MARINHA
    EXECUTE IMMEDIATE 'CREATE TABLE NAVIO_MARINHA(
        CODIGO VARCHAR2(4),
        NOME VARCHAR2(100),
        MODELO VARCHAR2(100),
        CAPACIDADE NUMBER(4),
        CONSTRAINT PK_NAVIO_MARINHA PRIMARY KEY (CODIGO)
    )';

    -- TABELA PIRATA
    EXECUTE IMMEDIATE 'CREATE TABLE PIRATA( 
        CPF VARCHAR2(11), 
        NOME VARCHAR2(100), 
        NASCIMENTO VARCHAR2(50), 
        RECOMPENSA NUMBER(10,2), 
        RUM_FAVORITO VARCHAR2(100),
        CONSTRAINT PK_PIRATA PRIMARY KEY (CPF)
    )';

    -- TABELA CAPITAO
    EXECUTE IMMEDIATE 'CREATE TABLE CAPITAO(
        CPF VARCHAR2(11),
        CONSTRAINT PK_CAPITAO_PIRATA PRIMARY KEY (CPF)
    )';
    
    -- TABELA NAVIO_PIRATA
    EXECUTE IMMEDIATE 'CREATE TABLE NAVIO_PIRATA(
        CODIGO VARCHAR2(4),
        NOME VARCHAR2(100),
        MODELO VARCHAR2(100),
        CAPACIDADE NUMBER(4),
        CPF_CAPITAO VARCHAR2(11) UNIQUE NOT NULL,
        CONSTRAINT PK_NAVIO_PIRATA PRIMARY KEY (CODIGO)
    )';
    
    -- TABELA TRIPULANTE
    EXECUTE IMMEDIATE 'CREATE TABLE TRIPULANTE(
        CPF VARCHAR2(11),
        COD_NAVIO_P VARCHAR2(4),
        CONSTRAINT PK_TRIPULANTE PRIMARY KEY (CPF)
    )';
    
    -- TABELA ALCUNHA
    EXECUTE IMMEDIATE 'CREATE TABLE ALCUNHA(
        CPF VARCHAR2(11),
        ALCUNHA VARCHAR2(100),
        CONSTRAINT PK_ALCUNHA PRIMARY KEY (CPF, ALCUNHA)
    )';
    
    -- TABELA PET
    EXECUTE IMMEDIATE 'CREATE TABLE PET(
        CODIGO VARCHAR2(4),
        CPF_DONO VARCHAR2(11),
        NOME VARCHAR2(100),
        ESPECIE VARCHAR2(100),
        CONSTRAINT PK_PET PRIMARY KEY (CODIGO, CPF_DONO)
    )';
    
    -- TABELA TERRITORIO
    EXECUTE IMMEDIATE 'CREATE TABLE TERRITORIO(
        QUADRANTE VARCHAR2(4),
        NOME VARCHAR2(100),
        CPF_CAPITAO VARCHAR2(11),
        CONSTRAINT PK_TERRITORIO PRIMARY KEY (QUADRANTE)
    )';
    
    -- TABELA EXPEDICAO
    EXECUTE IMMEDIATE 'CREATE TABLE EXPEDICAO(
        CPF VARCHAR2(11),
        QUADRANTE VARCHAR2(4),
        COD_NAVIO VARCHAR2(4),
        DATA_EXPEDICAO VARCHAR2(50),
        CONSTRAINT PK_EXPEDICAO PRIMARY KEY (CPF, QUADRANTE, COD_NAVIO, DATA_EXPEDICAO)
    )';
    
    -- TABELA CAPTURA
    EXECUTE IMMEDIATE 'CREATE TABLE CAPTURA(
        CPF_P VARCHAR2(11),
        CPF_M VARCHAR2(11),
        QUADRANTE VARCHAR2(4),
        COD_NAVIO VARCHAR2(4),
        DATA_CAPTURA VARCHAR2(50),
        CONSTRAINT PK_CAPTURA PRIMARY KEY (CPF_P, CPF_M, QUADRANTE, COD_NAVIO, DATA_CAPTURA)
    )';
    
    -- TABELA PROTEGE
    EXECUTE IMMEDIATE 'CREATE TABLE PROTEGE(
        CODIGO VARCHAR2(4),
        QUADRANTE VARCHAR2(4),
        CONSTRAINT PK_PROTEGE PRIMARY KEY (CODIGO, QUADRANTE)
    )';
end;